version: '3'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  app:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      API_SECRET: course_enrollment
      MONGO_URL : mongodb://mongo_db:27017/course_enrollment
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}